[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
[fmt]
single_line_statement_blocks = "multi"
sort_imports = true
multiline_func_header = "params_first"
contract_new_lines = true
override_spacing = true
