name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  FOUNDRY_PROFILE: ci
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: "pnpm"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install deps
        run: forge install
        

      - name: Check gas snapshots
        run: forge snapshot --check

      - run: pnpm install --frozen-lockfile
      - run: pnpm nx affected -t build --parallel=2
      - run: pnpm nx affected -t test --parallel=2